AWSTemplateFormatVersion: '2010-09-09'
Description: 'This stack is created for ECS Repository'

Resources:
  AstroRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "astro-devops-ecr-repository"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - "*"
          
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

      ImageScanningConfiguration: 
        ScanOnPush: "true"